[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules", "../Onchain DNS Import"]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
ffi = true

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@onchain-dns-import/=../Onchain DNS Import/"
]



